### ISSUE TITLE
Travis failing on re-render after registration

### ISSUE THREAD

**Issue by synapticarbors** [conda-forge/lightgbm-feedstock#1]
For some reason rendering the feedstock on Travis is failing:

https://travis-ci.org/conda-forge/lightgbm-feedstock/jobs/255873871

It's giving the same error about failing to apply the patch that I was having a hard time with originally. I had gotten it working in the `staged-recipes` PR and all of the tests passed.

@jakirkham Any idea what's going on?

**Comment by synapticarbors** [comment]
Forgot to apply changes to `.gitattributes` in the feedstock. #2 should address this.

**Comment by jakirkham** [comment]
There's not been a `conda-smithy` release with the `.gitattributes` change. So it has likely created the malformed patch using the currently released `conda-smithy`. Sorry! 😔 Hopefully I'll have some time to look at releasing a new `conda-smithy` soon. Have been swamped with other work of late. I'll try to send a PR to fix the feedstock with a hack for now.

**Comment by jakirkham** [comment]
Sorry missed your comment when responding. That PR should address it. If that doesn't work, would grab the patch straight from `staged-recipes` to make sure it is of a known working format.
