### ISSUE TITLE
scikit-learn 0.22 incompatability

### ISSUE THREAD

**Issue by xhochy** [conda-forge/lightgbm-feedstock#21]
We currently don't pin scikit-learn in the recipe but actually upstream limits it to `<=0.21.3` as 0.22 introduced changes that are incompatible to things in LightGBM.

**Comment by xhochy** [comment]
Updated the description as only master pins currently.

**Comment by synapticarbors** [comment]
@xhochy do you want me to add `<0.21.3` in the `run` requirements of the recipe?

**Comment by xhochy** [comment]
Yes, that would help.

**Comment by h-vetinari** [comment]
> @xhochy: We currently don't pin scikit-learn in the recipe but actually upstream limits it to `<=0.21.3` as 0.22 introduced changes that are incompatible to things in LightGBM.

Which incompatible changes were introduced? Are they tracked somewhere?

**Comment by h-vetinari** [comment]
Nevermind, I found it [here](https://github.com/microsoft/LightGBM/blob/master/docs/Python-API.rst):
> The last supported version of scikit-learn is 0.21.3. Our estimators are incompatible with newer versions.

**Comment by h-vetinari** [comment]
Also this issue: microsoft/LightGBM#2628

Scikit-learn had [reverted](https://github.com/microsoft/LightGBM/issues/2628#issuecomment-570289669) the breaking behaviour of `0.22.0` with `0.22.1`, but apparently there's still an issue left to resolve before lightgbm can be compatible again: scikit-learn/scikit-learn#16241.

There's already some [patches](https://github.com/microsoft/LightGBM/compare/sklearn) by @StrikerRUS on the lightgbm-side (see also [here](microsoft/LightGBM/pull/2721)) that await the resolution of this issue.

Finally, linking conda-forge/scikit-learn-feedstock#119 that's blocking #22.

**Comment by rth** [comment]
@h-vetinari I haven't really looked into all the related discussions of microsoft/LightGBM#2628 but if there was a regression in scikit-learn https://github.com/scikit-learn/scikit-learn/issues/16241 is not it. That just a inaccurate check in unit tests that can be ignored.

**Comment by h-vetinari** [comment]
Upstream has removed the incompatibility with sklearn 0.22 in microsoft/LightGBM#2949. Thanks @StrikerRUS & @rth for the work on this! So this issue should be closable with the next version of lightgbm.

**Comment by StrikerRUS** [comment]
This issue can be closed.
