### ISSUE TITLE
Is it possible to remove broken label from labels list?

### ISSUE THREAD

**Issue by StrikerRUS** [conda-forge/lightgbm-feedstock#59]
### Comment:

Due to [the old typo in the `version` field](https://github.com/conda-forge/lightgbm-feedstock/blob/ac1711fc9548afb6b9cff580f9103cf38ecb2853/recipe/meta.yaml#L6) (fixed in #49) there is a `broken` label at the package page.

![image](https://github.com/user-attachments/assets/9a880fb6-1481-4537-9215-9bfee7dd7f8f)

This results in a wrong version badge for the package:
![image](https://github.com/user-attachments/assets/d6fa85f0-2104-44e2-8c7e-fe51cef83426)

It can be solved via specifying `label=main` in shields.io badge constructor, but this feature isn't released yet: https://github.com/badges/shields/issues/2955.

**Comment by jameslamb** [comment]
Others can correct me if I'm wrong... but I think that label needs to stay, to prevent `conda install` from finding the package.

From the conda-forge docs:

> _As a matter of policy, we do not allow edits or the deletion of packages on conda-forge. This policy is very important as it increases the reliability and reproducibility of conda environments made with the conda-forge channel_
>
> _If you need to remove a package, please see the [section](https://conda-forge.org/docs/maintainer/updating_pkgs/#maint-fix-broken-packages) on marking packages broken._

I believe we're stuck with that package being there, and will need that change in https://github.com/badges/shields/issues/2955 to get a `conda-forge`-specific badge with the correct label.

**Comment by StrikerRUS** [comment]
Looked at https://api.anaconda.org/package/conda-forge/lightgbm and noticed the following:
```
...
    "versions": [
        "2.0.4",
        "2.0.5",
        "2.0.7",
        "2.0.10",
        "2.1.0",
        "2.1.1",
        "2.1.2",
        "2.2.0",
        "2.2.1",
        "2.2.2",
        "2.2.3",
        "2.3.0",
        "2.3.1",
        "3.0.0",
        "3.1.0",
        "3.1.1",
        "3.2.0",
        "3.2.1",
        "3.3.1",
        "3.3.2",
        "3.3.3",
        "3.3.4",
        "3.3.5",
        "4.0.0",
        "bee59dd269a93b093f2c610d4a6683a7ea87c63d3ea35c622123ce2c020b2abc",
        "4.1.0",
        "4.2.0",
        "4.3.0",
        "4.4.0"
    ],
    "latest_version": "bee59dd269a93b093f2c610d4a6683a7ea87c63d3ea35c622123ce2c020b2abc",
    "platforms": {
        "linux-64": "bee59dd269a93b093f2c610d4a6683a7ea87c63d3ea35c622123ce2c020b2abc",
        "linux-ppc64le": "bee59dd269a93b093f2c610d4a6683a7ea87c63d3ea35c622123ce2c020b2abc",
        "linux-aarch64": "bee59dd269a93b093f2c610d4a6683a7ea87c63d3ea35c622123ce2c020b2abc",
        "win-64": "bee59dd269a93b093f2c610d4a6683a7ea87c63d3ea35c622123ce2c020b2abc",
        "osx-64": "bee59dd269a93b093f2c610d4a6683a7ea87c63d3ea35c622123ce2c020b2abc",
        "osx-arm64": "bee59dd269a93b093f2c610d4a6683a7ea87c63d3ea35c622123ce2c020b2abc"
    },
...
```

I guess it's a bug. Probably `latest_version` field is computed by sorting `versions` alphabetically.

**Comment by StrikerRUS** [comment]
Found one similar issue about versions inconsistency: https://github.com/anaconda/anaconda-client/issues/561. Unfortunately, there are no responses in that issue.

Does anyone know which script is responsible for creating those json-files from `https://api.anaconda.org/package/`? It seems there is a lot of room for improvement.

**Comment by StrikerRUS** [comment]
Looks like [4.5.0 release](https://github.com/conda-forge/lightgbm-feedstock/pull/60) helped to place correct value in the `latest_version` field.

![image](https://github.com/user-attachments/assets/0ef6ec04-421a-438a-8e1e-18f10cac3b31)

**Comment by StrikerRUS** [comment]
@jameslamb Thank you so much for finding the right place to report this problem!
Sorry, I couldn't do that.
